language: java
before_script:
  - 'wget https://dl.dropboxusercontent.com/u/55284851/MineBuilder/MBServerApi-beta.zip'
  - 'unzip -jv MBServerApi-beta.zip MBServerAPI.jar'
  - 'find src/ 2>&1 | grep .java > sources.txt'
  - 'mkdir -v classes'
  - 'ls -lah'
script:
  - 'javac -cp ./MBServerAPI.jar:. -d classes -sourcepath src @sources.txt'
